const apiEndpoint = {
  login: "auth/login",
  stats: "stats",
  me: "auth/me",
  // feedback: "feedback",
  feedback: (search: string = "") => `feedback?organization_name=${search}`,
  // deleteFeedback: "feedback",
  deleteFeedback: (id: string | number) => `feedback/${id}`,
  forum: "forum",
  updateUser: (id: string | number) => `user/${id}`,
  approveFeedback: (id: string | number) => `feedback/${id}`,
  feedbackView: (id: string | number) => `feedback/${id}`,
  deleteFeedbackReview: (id: string | number) => `feedback/${id}`,
  getUsersByRole: (role: string) => `user?role_type=${role}`,
  // getUsersByRole: (role: string, search: string) => `user?role_type=${role}&search=${search}`,
  // getUsersBySearch: (name: string) => `user?search=${name}`,
  getUserById: (id: string | number) => `user/${id}`,
  getCommunityPost: (postId: string | number) => `community/post/${postId}`,
  approveCommunityPost: (postId: string | number) => `community/post/${postId}`,
  postCommentUpdate: (postId: string | number) => `community/post/${postId}`,
  // deleteCommunityPost: (postId: string | number) => `community/post/${postId}`,
  userActivity: (type: string) => `stats?type=${type}`,
  peakVisitors: (type: string) => `stats?type=${type}`,
  topInsuranceUsed: (type: string) => `stats?type=${type}`,
  ageGroups: (type: string) => `stats?type=${type}`,
  trendingTopics: (type: string) => `stats?type=${type}`,
  getFlagReports: (searchText) => `community/post-reports?search=${searchText}`,
  getAllCommunityPosts: "community/post",
  deleteFlagReport: (id: string | number) => `community/post-reports/${id}`,
  // DELETE API endpoints
  deleteCommunityPost: (postId: string | number) => `community/post/${postId}`,
  deleteComment: (commentId: string | number) => `comment/${commentId}`,
  getNotifications: "user/notifications",
  // getRecentSearches: "recent-search",
  getRecentSearches: (userId: string | number) => `recent-search/${userId}`,
  // getCommentsType: (Id: string | number) => `community/post/comment/${Id}`,
  // getCommentsType: (Id: string | number) => `community/post/comment/${Id}`,
  getCommentsType: (Id: string | number) => `community/post/comment/${Id}`,
  getPatientDetails: (Id: string | number) => `user/${Id}`,
  getSinglePost: (post_id: string | number) => `/community/post/${post_id}`,
  getSingleComment: (comment_id: string | number) =>
    `/community/post/comment/${comment_id}`,
  getSingleReport: (id: number) => `/community/post/report/${id}`,
};

export default apiEndpoint;
